import { createContext } from 'react';

const id = Date.now(); //TODO: this id should be generated by a database - for now we are going with a timestamp
export const defaultUser = {
  name: `RandomUser${id}`,
  id
};

export const UserContext = createContext(defaultUser);
